language: python

os:
  - linux
  - osx

dist:
  - xenial
 
python:
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - touch ./M3; chmod 0755 ./M3
  - pip install -r requirements.txt
  - PATH=.:$PATH pip install .
