language: python
dist: trusty

os:
  - linux
  - osx
 
python:
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - touch ./M2; chmod 0755 ./M2 # fake M2 executable
  - pip install -r requirements.txt
  - PATH=.:$PATH; pip install .
